### ISSUE TITLE
Image zoom

### ISSUE THREAD

**Issue by hupo376787** [tiny-express/flutter_scroll_gallery#1]
Hi, it will be great if the image can be zoom in and out.

**Comment by dthongvl** [comment]
thanks, I will consider in the next version 👍

**Comment by hupo376787** [comment]
Thanks for your great work.

**Comment by dthongvl** [comment]
I've finished the zoom feature. Waiting for your feedback. :wink:

**Comment by hupo376787** [comment]
Hi, when zoom out an image to a small size, smaller than screen size, then the widget can't be slide to next one.

And another, I don't know it's a bug or something. When double tap an image, the image zooms in, then drag it, the widget slide to next image, not pan. I think it's better to pan first, when go to the image border, then slide to next image.

Here is the [Video](https://github.com/hupo376787/Test/blob/master/89f968e11b29389a4fbf75e58877aa7a.mp4)

**Comment by dthongvl** [comment]
Sorry for the late reply, I will check this. @TuanAnhNguyen69

**Comment by TuanAnhNguyen69** [comment]
> Hi, when zoom out an image to a small size, smaller than screen size, then the widget can't be slide to next one.
> 
> And another, I don't know it's a bug or something. When double tap an image, the image zooms in, then drag it, the widget slide to next image, not pan. I think it's better to pan first, when go to the image border, then slide to next image.
> 
> Here is the [Video](https://github.com/hupo376787/Test/blob/master/89f968e11b29389a4fbf75e58877aa7a.mp4)

@hupo376787 This was fixed in version 0.1.1. Thanks for your contribution.
