### ISSUE TITLE
should add currentIndex to the constructor

### ISSUE THREAD

**Issue by infodog** [tiny-express/flutter_scroll_gallery#2]
The case is that : we show a list of images on the screen, when the user tabs one, we show the flutter_scroll_gallery. But we need to display the image which the user just tabbed as the big one.
So we need to input the index of the image to the constructor.

**Comment by TuanAnhNguyen69** [comment]
@infodog Hi there! I've just supported initial index in ver 0.1.1. Thanks for your suggestion!
