### ISSUE TITLE
Black Background for flutter scroll gallery widget

### ISSUE THREAD

**Issue by essare** [tiny-express/flutter_scroll_gallery#3]
any way to change the black background at least replace it with white color ? thank for this awesome widget :+1: 

![device-2019-01-09-130902](https://user-images.githubusercontent.com/17065084/50898795-1f5d1a80-1408-11e9-9a51-bda61409ace8.png)

my code snippet
`  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      color: Colors.white,
      child: ScrollGallery(
        getImages(widget.product),
        interval: new Duration(seconds: 3),
        borderColor: Colors.pink,
        fit: BoxFit.fill,
        height: 400,
      ),
    ));
  }
}`

**Comment by dthongvl** [comment]
Please check #4 . Thank you. 😄
