### ISSUE TITLE
Version 0.1.0 is not on pub yet

### ISSUE THREAD

**Issue by RicCu** [tiny-express/flutter_scroll_gallery#4]
This version has at least one very important feature: it allows to change the background color, solving #3, however the latest version available on [pub](https://pub.dartlang.org/packages/flutter_scroll_gallery) is 0.0.2

**Comment by dthongvl** [comment]
Sorry for the late reply, I will publish it asap after solved #2

**Comment by TuanAnhNguyen69** [comment]
@RicCu I've just published version 0.1.1 with some new feature and bug fixed. Thanks for your reminder!!
