### ISSUE TITLE
Navigate by Index

### ISSUE THREAD

**Issue by essare** [tiny-express/flutter_scroll_gallery#5]
any way to select image by its index id ? or know which image index is displayed
some thing like this
``` Dart
updateCallback: (index) {
        setState(() {
          _selectedImgIndex = index;
        });
      },
```

**Comment by TuanAnhNguyen69** [comment]
@Ess-Soft I have supported a handler that provides you the current index in ver 0.1.1. Hope that helps.

**Comment by tiny-express** [comment]
thanks @TuanAnhNguyen69
